name: CI

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Project dependencies
        run: yarn install
      - name: Lint code
        run: yarn preflight
      - name: Build code
        run: yarn build
